version: "3.8"
services:
  back: 
    build: ./back
    ports: 
      - "8000:8000"
    networks:
      - musicworld
    depends_on:
      - mongodb
    restart: always
  
  front: 
    build: ./front
    ports: 
      - "3000:3000"
    networks:
      - musicworld
    depends_on:
      - back
    restart: always
    stdin_open: true
    tty: true
  
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    networks:
      - musicworld
    volumes:
      - ./database:/data/db
    restart: always
    
      

networks:
  musicworld:




   
  